### ISSUE TITLE
Blogs single page : Please remove breadcrumbs as per PSD

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/In-Touch-Physio#13]
![17](https://cloud.githubusercontent.com/assets/13309806/12668944/c4e2cd04-c610-11e5-9bb1-b8e388ed375b.png)

**Comment by Rahul-titan** [comment]
Breadcrumbs has to be there for all single posts. Sometimes designers miss this thing. Please confirm with your TL.
