### ISSUE TITLE
Admin (About Helen Page) : Featured image should be full width as per PSD

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/In-Touch-Physio#14]
![16](https://cloud.githubusercontent.com/assets/13309806/12668962/00473f6a-c611-11e5-83f1-aeec84b47355.png)

**Comment by Rahul-titan** [comment]
Since it is a featured image. upload fullwidth image is the solution

**Comment by romatitan** [comment]
@Rahul-titan 
The page featured image wrapper is W:870px, the same with the given design.
However, the uploaded featured image seems to be smaller in front end, but have a size of 3504x2336 px.
Kindly check this issue again.

![image](https://cloud.githubusercontent.com/assets/12888048/12969092/6cd3cdce-d0b6-11e5-9535-b260379e31a1.png)
![image](https://cloud.githubusercontent.com/assets/12888048/12969095/71909e8c-d0b6-11e5-9eaa-4f889cc013fe.png)
![image](https://cloud.githubusercontent.com/assets/12888048/12969100/73a09ce0-d0b6-11e5-9e22-723baf838984.png)

**Comment by romatitan** [comment]
Kindly check again.
Ref: 
http://mckee-family-funerals.stage.titanweb.com.au/about-us/
