### ISSUE TITLE
Homepage - Recent Blog: There's a large unused space

### ISSUE THREAD

**Issue by romatitan** [titan-cebu/In-Touch-Physio#153]
![image](https://cloud.githubusercontent.com/assets/12888048/13482941/3812a49a-e12b-11e5-9a84-225b62d4fe13.png)

**Comment by Rahul-titan** [comment]
Please add more content and test it again

**Comment by romatitan** [comment]
Change the label to enhancement.
Align the item to center in small resolution. This is to maximize the use of space.
