### ISSUE TITLE
Admin (Make A Booking With HELEN): Form description is not displaying. Applicable for all forms

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/In-Touch-Physio#9]
![11](https://cloud.githubusercontent.com/assets/13309806/12668833/71511df4-c60f-11e5-9465-fdb84e893aa5.png)

**Comment by Rahul-titan** [comment]
Theme options -> [gravityform id="3" title="true" description="false"] 
If description ="true",   description displays
